# Site settings
title: Ƀitlabs
email: mail@bitlabs.dev
url: https://bitlabs.dev
description: "Ƀitlabs is contributing to decentralised autonomous organisations in NFT and Web3."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: Ƀitlabs

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: 
    url: 
  - title: 
    url:
  - title: 
    url: 
  - title: 
    url: 
  - title: 
    url:

# Build settings
markdown: kramdown
permalink: pretty

theme: jekyll-theme-slate